### ISSUE TITLE
Improve the documentation on TypeExpression sub sets

### ISSUE THREAD

**Issue by amedranogil** [universAAL/middleware#1]
I am working on Security features, I am heavily using the TypeExpression mechanism for example to define the set of instances to apply a specific Security restriction.

As I started to use the TypeExpression mechanism I have a lot of doubts of all the options that this has, and I don't quite know which to use.

For example I want to declare a Type expression declaring all members of a class should apply. For this I found the TypeURI class; but the Javadoc on this class is far from complete, and does not even seem to correlate to the javadoc of TypeExpresion (BTW very good).

Please add sensible Javadoc to all subclasses of TypeEpression. I suggest since the TypeExpression javadoc says these are "epresentations of "sets of individuals by formally specifying conditions on the individuals' properties", It would be good to have the representation of the described set in the javadoc of each class.

This is important not only for me, as the security mechanism exposes this to the developer; so developers need deeper information on this system.

**Comment by cstockloew** [comment]
Done.
