### ISSUE TITLE
Remove usage of ModuleConfigHome

### ISSUE THREAD

**Issue by cstockloew** [universAAL/middleware#10]
ModuleConfigHome and its subclass BundleConfigHome have been deprecated some time ago (june 2014) but we still use it. It was replaced by ModuleContext.getConfigHome and ModuleContext.getDataFolder.

All depending modules should be updated to use the new way, to enable us to remove these classes completely.

**Comment by cstockloew** [comment]
I think I got them all (and I hope I got them all right).
Is it OK to remove the deprecated classes?

**Comment by Alfiva** [comment]
ok, I guess it will be the fastest to way to find any remaining usages...

**Comment by cstockloew** [comment]
Files are deleted, closing issue.
