### ISSUE TITLE
How to set per-ServiceProfile specific values to variable inputs

### ISSUE THREAD

**Issue by cstockloew** [universAAL/middleware#442]
_Originally Opened: @Alfiva (2014-10-08 17:55:30_)
_Originally Closed: 2014-11-27 12:18:23_

Consider the idea of the following scenario:

-I have a ServiceProfile for a DimmerActuator that allows setting its value, to this very specific DimmerActuator X
-I want to call it with a ServiceRequest by addressing this specific DimmerController X with a value Y=75

Now consider the following code for specifying the ServiceProfile:

ProcessInput input = new ProcessInput(IN_DEVICE_URI);
input.setParameterType(actuator.getClassURI());

ProcessInput inputValue = new ProcessInput(IN_SET_VALUE_URI);
inputValue.setParameterType(TypeMapper.getDatatypeURI(Integer.class));

MergedRestriction r = MergedRestriction.getFixedValueRestriction(
		DeviceService.PROP_CONTROLS, actuator);

profiles[1] = setValue.getProfile();
profiles[1].addInput(input);
profiles[1].addChangeEffect(ppath.getThePath(),inputValue.asVariableReference());
profiles[1].getTheService().addInstanceLevelRestriction(r,
	new String[] { DeviceService.PROP_CONTROLS });

Cardinalities and other additional code omitted. The important here is how is the input for the DimmerActuator declared. In this code, it is set both as an Input of type DimmerActuator, AND as an InstanceLevelRestriction with the actual value of the DimmerActuator X. NOT as an input.asVariableReference.

The question is: is this a proper way to define this scenario? What ServiceRequest will match this Profile? Right now a Request that uses addValueFilter would not match, stating that the number of inputs in request is insufficient. Also, take into account that this is how ZB exporter makes its services, which also means that at some point in time this worked.

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by cstockloew** [comment]
_Original author: @amedranogil (2014-10-08 23:20:02)_

I had this very same issue before the summer (sent question in private email &quot;Service Not Found&quot;). 

I think the solution should also allow to match the service profile of the concrete DimmerActuatorX by not providing the explicit DimmerActuatorX, but restrictions that match this device (which is what we were attempting).

So if DimmerActuatorX has_location kitchen, a service request for dimming Actuators in the kitchen can be issued, and the service profile of then DimmerActuatorX is match (along with other actuators that might match the request).

**Comment by cstockloew** [comment]
_Original author: @Alfiva (2014-10-13 09:30:16)_

I knew I had seen this somewhere else but I couldn't find it. Anyway, I just found this doing some custom quick apps, it is not something that breaks any existing code. But still it would be interesting to address this. Did you create a tracker item for that issue? If so, we could merge or remove this one.

**Comment by cstockloew** [comment]
_Original author: @Alfiva (2014-11-05 18:36:42)_

BUMP. To maximum  priority. Assigned to Carsten.

AS more pilots are starting to work with LDDI and their own exporters, this situation becomes more critical.

The discussion from before summer mentioned by Alejandro ends without a solution, and with the though: &quot;My worry right now is that in order to make the service match the parameter has to be the exact instance (the java instance) as the one provided for the registration of the service profile, or that the matchmaking is using the full equivalence (checking the whole RDF graph, even if type and URI are equal).&quot; And I fear this is the problem too.

This should be solved ASAP. And I insist that I think at some point in the past (maybe as back as PERSONA) this used to work, because ZigBee exporter works (worked) this way.

**Comment by cstockloew** [comment]
_Original author: @cstockloew (2014-11-05 18:55:50)_

From tutorial (Service Bus Details):

	Service dim = createService(SERVICE_DIM, dev);
	dim.addFilteringInput(INPUT_LAMP_URI, Lamp.MY_URI, 1, 1, ppControls);
	dim.addInputWithChangeEffect(INPUT_LAMP_BRIGHTNESS,
		TypeMapper.getDatatypeURI(Integer.class), 1, 1, ppBrightness);
	profiles.add(dim.getProfile());

**Comment by cstockloew** [comment]
_Original author: @Alfiva (2014-11-06 11:30:00)_

That's OK for handling arbitrary Lamps and read them from the request, but the idea here is that the provided service handles requests *only* for a certain Lamp (e.g. ...#lamp3). Is it possible to have that kind of restriction, and at the same time be able to match it for requests addressing that lamp3 but also addressing &quot;any&quot; Lamp?

-BTW I tried out this profile:

ppath = new PropertyPath(null, true, new String[] { DeviceService.PROP_CONTROLS, Sensor.PROP_HAS_VALUE });
r = MergedRestriction.getFixedValueRestriction(DeviceService.PROP_CONTROLS, new SwitchController(CPublisher.DEVICE_OWN_URI));
getTheValue = new SCalleeProvidedService(SERVICE_GET_STATUS_URI);
profiles[0] = getTheValue.getProfile();
output = new ProcessOutput(OUTPUT_STATUS);
output.setCardinality(1, 1);
profiles[0].addOutput(output);
profiles[0].addSimpleOutputBinding(output, ppath.getThePath());
profiles[0].getTheService().addInstanceLevelRestriction(r, new String[] { DeviceService.PROP_CONTROLS });

-And tried to call it with this request:

setStatus = new ServiceRequest(new DeviceService(), null);
setStatus.addValueFilter(new String[] { DeviceService.PROP_CONTROLS },
			new SwitchController(CPublisher.DEVICE_OWN_URI));
setStatus.addRequiredOutput(EXPECT_OUTPUT, new String[] {
			DeviceService.PROP_CONTROLS, SwitchController.PROP_HAS_VALUE });

-But I get no_matching and the MW log says:

Mismatch detected: input in offer not defined in request
mismatch code: 1023
detailed mismatch message:  An input parameter is given in the offer, e.g. a filtering value, but the service request does not provide this input parameter. The exact parameter is not determined, only the number of parameters has been found to be problematic.248

-Despite I removed usage of ProcessInputs both in profile and request (AFAIK addValueFilter uses fixed value restriction, no ProcessInput).

**Comment by cstockloew** [comment]
_Original author: @Alfiva (2014-11-12 10:20:14)_

Can we get any update on this? Right now there is at least one pilot blocked by this, so if in the end this kind of desired behaviour is not currently possible, please let us know, so we can change the ServiceProfiles of LDDI exporters to something that actually works.

**Comment by cstockloew** [comment]
_Original author: @Alfiva (2014-11-20 10:52:35)_

That solution doesn't even work. I have created two applications, each with the same profile as suggested, with filtering Input, and then analyzing in the callee if it gets the right device in the input, but I wasn't sure what to return if the input device is not the right one for the callee: no matching? denied? null? Anyway, it doesn't matter, because the service bus is always only calling the last application callee registered.

I assumed I would have to determine in my service request that I want all matching callees to be called, not just &quot;the first one&quot;, and that I should use an AggregatingFilter for that, but could not find how to do that: I can't find the service bus manual sent some time ago and the ref doc says nothing about this.

Please provide a solution for this ASAP.

**Comment by cstockloew** [comment]
_Original author: @cstockloew (2014-11-25 04:50:06)_

Hi and sorry for the delay. This was not an easy one...

First the &quot;easy&quot; questions:

- &quot;but I wasn't sure what to return if the input device is not the right one for the callee&quot;:
The lighting sample uses this response:
    ServiceResponse invalidInput = new ServiceResponse(
	CallStatus.serviceSpecificFailure);
    invalidInput.addOutput(new ProcessOutput(
	ServiceResponse.PROP_SERVICE_SPECIFIC_ERROR, &quot;Invalid input!&quot;));
I'm not sure if this is the best way to do it, but it's currently done that way.

- &quot;I want all matching callees to be called, not just 'the first one'&quot;:
It should call all callees with a matching profile, but only one profile per callee. Can you check that this is the case? Have you registered the two profiles for different callees or for the same callee?

- &quot;..and that I should use an AggregatingFilter for that&quot;:
There are two types of AggregatingFilters. What you mean is the &quot;service selection filter&quot;. This, however, has the opposite effect - it ~reduces~ the number of callees to 1 even if there is more than one. But you want all callees to be called. AggregatingFilter cannot help here.


----------------
-- Analysis and discussion
-- (you can skip this if you are not interested)
----------------

Now to your main question (the example in your first post):
I tried to find out when this behaviour was changed (as you said it was working before) but I could not find anything like this. Either this was really in PERSONA a long time ago (and isn't working since) or I'm missing something (I didn't look at it in detail, so I guess I'm just missing something).

However, this is how it works:
every value (concrete value, like &quot;DimmerActuatorX&quot;, and variable values in form of ProcessInputs, like IN_SET_VALUE_URI) need to be set as restriction in the profile. The restrictions of request and profile are matched against each other by the matches-method in DataRep. When the matches-method finds a concrete value it just checks that the values in profile and request are equal (should be 'equals', not the same Java object). When the matches-method finds a ProcessInput in the profile (and a concrete value in the request), it stores this mapping in the HashMap 'context': the URI of the ProcessInput is the key and the value from the request is the value of HashMap.

In your example, you have only one call to 'addInstanceLevelRestriction' to set the actuator to a concrete value. But it should be 2 calls to set actuator and value. So, it should be something like (just writing down, it's untested):

	MergedRestriction resControls = MergedRestriction.getFixedValueRestriction(
		DeviceService.PROP_CONTROLS, actuator);
	MergedRestriction resValue = MergedRestriction.getFixedValueRestriction(
		Device.PROP_VALUE, inputValue.asVariableReference());
	addInstanceLevelRestriction(resControls, ppControls);
	addInstanceLevelRestriction(resValue, ppValue);
	addInput(inputValue);
	...

The matches-method would then check that at ppControls profile and request have the same value (here: DimmerActuatorX), and it would also store the concrete value at ppValue given by the request in the context HashMap (here: context would store the tuple (IN_SET_VALUE_URI, 75)).

The next step in the matchmaking is checking that each parameter in the profile was set to a concrete value by the request (here: the one ProcessInput 'IN_SET_VALUE_URI' must be set, meaning: there must be an entry in context). This is a simple check: we just check that the size of the context-HashMap has increased by the number of ProcessInputs that are defined in the profile. And this is where you get the error &quot;Mismatch detected: input in offer not defined in request&quot; because you do not have a ProcessInput in your restrictions.

Please note, that the method 'addInput' is only a formality. It is not really used in the matchmaking. Instead, it is only important that the ProcessInputs are mentioned in the restrictions with myInput.asVariableReference (maybe they are used, I'm not sure at the moment).


Unfortunately, there is a bug in the method 'addInstanceLevelRestriction' (I just discovered that) and that's why the code snippet above does not work. The problem is as follows:
when you add a FixedValueRestriction (formally, it's owl:DataHasValue / owl:ObjectHasValue, in OWL1 just owl:hasValue, so: hasValue = fixedValue) with the method addInstanceLevelRestriction then it stores 2 things:
1. the restriction itself
2. a counter for the number of hasValue restrictions

The counter is always increased no matter if the value is a concrete value or a ProcessInput. And this is wrong: the counter should only be increased in case of a ProcessInput. Otherwise, the matchmaking expects the 'context' to be increased but it does not increase for concrete values. For the code snippet above it currently expects the context to be increased by 2 (for the 2 calls to 'addInstanceLevelRestriction' which add 2 hasValue restrictions), but there is only 1 ProcessInput.

So, the following code should be the correct one (once the bug is fixed):

	dim.addInstanceLevelRestriction(MergedRestriction.getFixedValueRestriction(
		propPath[propPath.length - 1], actuator),
		propPath);
	dim.addInputWithChangeEffect(IN_SET_VALUE_URI,
		TypeMapper.getDatatypeURI(Integer.class), 1, 1, ppBrightness);

The first line could be simplified by adding a new method to the class 'Service':
addFilteringValue(Object value, String[] propPath);


----------------
-- Workaround
----------------

1.
The easiest way is to use the approach in the lighting sample: do not define the concrete value in the profile. Instead use the type. If the service is called with an individual that is not handled by the service, return an invalidInput response (see above).

2.
Another way (really a hack): is to manually decrease the internal counter by 1 ~before~ any call to 'addInstanceLevelRestriction':
	dim.setProperty(Service.PROP_NUMBER_OF_VALUE_RESTRICTIONS, Integer.valueOf(-1));
	dim.addInstanceLevelRestriction(MergedRestriction.getFixedValueRestriction(
		propPath[propPath.length - 1], actuator),
		propPath);
	dim.addInputWithChangeEffect(IN_SET_VALUE_URI,
		TypeMapper.getDatatypeURI(Integer.class), 1, 1, ppBrightness);
If you have more than one concrete value, you have to set this as negative value (for 2 concrete values, you set Integer.valueOf(-2) etc).


I'm afraid we have to use one of these workarounds (I prefer the first one). When the bug is fixed, it is only available in the next release 3.3.0.

Hope, it helps anyway.

**Comment by cstockloew** [comment]
_Original author: @Alfiva (2014-11-27 12:18:23)_

Thanks for the thorough explanation, I will get to this as suggested, and going point by point:

-What to return for non-matching inputs: I think I tried service-specific-error, but because I couldn't make it work I thought I was doing something wrong.
-One profile per callee: I was using 2 separate bundles, so that's 2 different callees each with a similar profile. I will look at this again, but anyway this was just the test. The actual use for the ZB exporter (and other ones) was having 1 callee with multiple similar profiles (e.g. each new connected door actuator device adds a new serviceprofile to the single callee of door actuators).
-Aggregating filters: OK, so no aggregating filters for this issue.

About the rest of the discussion, I try to solve some of your doubts:
When I said &quot;it worked before&quot; I was in fact referring to the PERSONA ages, since that is that last time I have had real ZB devices to play with - so I guess matchmaking changed (or was fixed) leaving the ZB exporter strategy of 1 calle X profiles outdated.

In my tests I had tried the profile you describe (fixed value instance + fixed value asVarRef) but then I guess the bug you mention would manifest, so I tried many other profile combinations.

So, if I get it right, once the counter bug is solved, I will be able to use the 1 callee X profiles with the suggested code?

In the meantime I will retrofit the ZB exporter (and tell Ibermatica to do the same) with the first workaround you suggest, since the second is a hack, and Helmi showed me yesterday they are using that first method too in the German pilots.

Then I'll see if I revert back to the old style exporter in 3.3.0.
Thanks again for the support - issue closed.

**Comment by cstockloew** [comment]
_Original author: @Alfiva (2014-12-01 11:40:18)_

Just one small follow up:

The ZB exporter does use in fact separate Callees, 1 per device, opposite to what I initially said of 1 Profile per device in a singleton Callee. I also made my test with different Callees, but now I realize there was a problem with them (all profiles had same URI). This was however not the point of the bug/issue, but I thought you would like to know this.

What on the other hand is the point of the issue is calling *all* the devices with one single request, e.g. &quot;turn on ALL lights&quot;. This cannot be achieved with the workaround as it requires an input as variable reference, but anyway, it is a workaround so as long as the final fixed solution works I am OK with that - but pilots should know that this specific feature is currently disabled until 3.3.0.

**Comment by cstockloew** [comment]
issue cloed on 2014-11-27 12:18:23

**Comment by ivadym** [comment]
Hello,

I am not sure that this bug has been solved since I am not able to match certain services associated with specific devices, even using the proposed hack. In fact, the `setProperty` method does not even modify the value of `PROP_NUMBER_OF_VALUE_RESTRICTIONS`.

Specifically, I am trying to offer exclusive services for specific actuators:

```
turnOn.addFilteringInput(INPUT_DEV, ValueDevice.MY_URI, 1, 1, PPATH_CONTROLS);
turnOn.addInstanceLevelRestriction(MergedRestriction.getFixedValueRestriction(DeviceService.PROP_CONTROLS, actuator), PPATH_CONTROLS);
turnOn.getProfile().addChangeEffect(PPATH_VALUE_DEVICE, new Integer(100));
profiles[i++] = turnOn.getProfile();
```

**Comment by Alfiva** [comment]
Here is a code I have recently used which I know works OK with 3.4.2-SNAPSHOT for this issue. It uses the NUMBER_OF_VALUE_RESTRICTIONS hack.

```
public static ServiceProfile profile_getExactDeviceHack(){
	DeviceService getDevice = new DeviceService(SERVICEURI);
	getDevice.setProperty(Service.PROP_NUMBER_OF_VALUE_RESTRICTIONS, Integer.valueOf(-1));
	
	getDevice.addInstanceLevelRestriction(MergedRestriction.getFixedValueRestriction(
		DeviceService.PROP_CONTROLS, new TemperatureSensor(Activator.PREFIX + "myDevice")),
		new String[] { DeviceService.PROP_CONTROLS });
	
	ProcessOutput output = new ProcessOutput(OUTPUTURI);
	output.setParameterType(TemperatureSensor.MY_URI);
	getDevice.getProfile().addOutput(output);
	getDevice.getProfile().addSimpleOutputBinding(output, new String[] { DeviceService.PROP_CONTROLS });
	getDevice.addInstanceLevelRestriction(MergedRestriction.getAllValuesRestriction(DeviceService.PROP_CONTROLS, TemperatureSensor.MY_URI),
		new String[] { DeviceService.PROP_CONTROLS });
	return getDevice.getProfile();
}
```

Is this how you tried the hack? Notice the -1 hack to be applied before anything else. If you don't the property may become set and not allow changes later.
Now, this code is for retrieving the device, as output, but I don't see why it wouldn't work for change effect.

**Comment by amedranogil** [comment]
I have some doubts this will be useful. 
If you want to tie the service profile to a device, then you suggest to add an instance level restriction with fixed value to the device itself. For me this means that the service request must match exactly that device, thus powerful matchmaking possibilities (such as, "turn on any device in this location") are lost (unless you add all the possible profiles with their respective restrictions, which make little sense).

**Comment by Alfiva** [comment]
If I get it correctly the matchmaking should get this anyway. After all, buried in the posts the question was:

> Is it possible to have that kind of restriction, and at the same time be able to match it for requests addressing that lamp3 but also addressing "any" Lamp?

I have tried with the hacked profile, and it still responds to requests asking for any device (value type restriction: Device). I guess that woud work as well with other restrictions like location?

**Comment by ivadym** [comment]
The hack is effective, the problem was that I had a wrong concept about the restriction of `addFilteringInput`. By eliminating it, the purpose of assigning services to specific devices has been achieved.

Thanks!
