### ISSUE TITLE
Improve JUnit verbosity configuration

### ISSUE THREAD

**Issue by cstockloew** [universAAL/middleware#481]
improve the verbosity of JUnit by configuring the log level of JUnitModuleContext to a env variable.

**Comment by amedranogil** [comment]
It will allow devs to selec which level they are intested in, and deactivate all logs during CI.
CI will run first w/o logs, and if there is a build failture it will run only the failed modules with full log.

**Comment by cstockloew** [comment]
The log level can be adapted already with
 ((JUnitModuleContext) mc).setLogLevel(LogLevel.XXX);
It's just not intuitive/not documented.

What about this: instead of re-running the tests, could junit store all logs and print them on error? Thing is, sometimes a unit test fails under certain circumstances, but not always. If there is an error and you re-run the test, it might be that the second run will not fail.

**Comment by amedranogil** [comment]
I'm thinking also from a developer perspective, by default they would like to see logs on the console.
so we can define an env variable that when activated avoids the [the console appender](https://github.com/universAAL/middleware/blob/master/middleware.core/mw.container.junit/src/main/java/org/universAAL/container/JUnit/JUnitModuleContext.java#L52).

Regardless of the console verbose it is indeed nice (even for developers) to have the full log in target folder. So we coul add a file appender to write in the logs into files too.

what should the env variable be?

**Comment by amedranogil** [comment]
The property that disables JUnitModuleContext loggin is: org.universAAL.junit.console.output 
run with -Dorg.universAAL.junit.console.output=false (or configureit in your pom, settings or profile) to disable.

**Comment by cstockloew** [comment]
When I set -Dorg.universAAL.junit.console.output=false then mw.service.bus.core does not work anymore. It seems like it is stuck in an endless loop.

**Comment by amedranogil** [comment]
this is odd, I only use this flag to skip the console appender creation.
check if there is some kind of dependency on that. (BTW, try to use the log functions instead of system.out)

**Comment by amedranogil** [comment]
Fixed, there was a stupid NPE when trying to log an error (all because I wanted to keep the red-toned errors)
