### ISSUE TITLE
Better Serialization for Anonymous nodes

### ISSUE THREAD

**Issue by amedranogil** [universAAL/middleware#5]
when an anonymous node is serialised it is always done so with `_:BNXXXXX` this has the scope of only the serialization being done.

There are cases where this is very limited and we have 2 cases right now:
1. The REST API relies on the Process URI to deliver responses from remote callees, but with current serialization the anonymous Processes will always be de same.
2. Interfacing with other semantic systems. Specifically the CHe database. If I introduce an `_:BN00000` CHE will transform into another URI like `_:node1b0ic7gpex464` when this is parsed it is reassigned as `urn:anonymous:_:a9fef4bcb9a0f7c2:c78` when I query again the DB for it there is obviously no response. So the reference is lost.

Serialization needs to be consistent. For applications to access the reference, anonymous serialization name should also be accessible through a method (because getURI != URI serialzation).

**Comment by Alfiva** [comment]
1: The workaround is that service callers buld their request with a specific URI, instead of using an empty constructor that will give calls an anonimous URI.

2: It you introduce a blank node _:BN00000 into CHE, by definition you cannot get it back, since blank nodes cannot be "called". The _:node1b0ic7gpex464 is just an internal reference in the CHE to identify a blank node, but IIRC is only in memory, it is not suppossed to be "used". And yes, when parsed it will be given an anon URI, because IIRC _:node1b0ic7gpex464 is a Sesame-specific. I may be wrong in some of the assumptions, but the bottom line is: you cannot call by their name a blank node, because they have no name.

**Comment by amedranogil** [comment]
I assumed that blank nodes could be called back as long as you maintaned the internal reference. 
eg: I introduced `_BN:00000` when I describe the object I get `?o ?p _:nodeWhatever . ` I have to test it but If I describe again `_:nodeWhatever` I should get that object.

**Comment by Alfiva** [comment]
you are making me doubt, but what I understand is that blank nodes are nameless, if you introduce a node as _:BN000000, it may later appear as _BN000001 _:BN0234223 or any other blank node denomination (  _:  ). That's the purpose of blank nodes. If you want to "get it back" you would have to do it indirectly, like if you add
pre:mynode pre:myprop _:BN00000
you get it with ?b in
pre:mynode pre:myprop ?b

**Comment by cstockloew** [comment]
Alvaro is right, they are locally scoped. As you can see in the [RDF 1.1 Concepts](https://www.w3.org/TR/rdf11-concepts/#section-blank-nodes):

> Blank node identifiers are local identifiers that are used in some concrete RDF syntaxes or RDF store implementations. They are always locally scoped to the file or RDF store, and are not persistent or portable identifiers for blank nodes.

Also, the [turtle serialization](https://www.w3.org/TR/turtle/#BNodes) (example 16/17) even avoids serialization of blank nodes, if possible. Only in rare cases, a blank node is serialized (e.g. when occuring as root node and rdf:object), but then it's locally scoped.

If you need to access these nodes across different queries, you have to give them a non-anonymous URI.

**Comment by amedranogil** [comment]
two other workarounds for 1 are:
1. the REST API component manages anonymous URIs before processing them
2. the bus manages anonymous URIs like the context bus does.

**Comment by amedranogil** [comment]
I have solved the anonymous thing (with Alvaro's tip).
But I still have an issue with the serializer.
