### ISSUE TITLE
How to disable JGroups - SLP Discovery and peering functions?

### ISSUE THREAD

**Issue by amedranogil** [universAAL/middleware#8]
#In Cloud environments it may be interesting to disable JGroups and SLP discovery and peering functions so it is not continuously searching for peers; in a network where there will be harldy any chance for it; and in some cases it is even counter productive as multicasting will cause network problems (in case of UPM running universAAL in the public network causes broadcast storms that disable the whole network).

I have attempted editing etc/mw.connectors.discovery.slp.core.cfg as well as etc/mw.managers.aalspace.core.cfg and etc/mw.modules.aalspace.core.cfg setting everything to false, or increasing the frequencies, YET when running other uAAL instances it gets detected.

BTW: haven't tested thoroughly but it seems that running two instances (default distro.karaf) on the same network by default the second instance will go to an infinite loop attempting to launch the aalspace manager.

**Comment by Alfiva** [comment]
Some pilot asked me preciesely about the same. The solution I proposed was increasing the discovery period (I wasn't sure if SLP could be disabled at all). Here is my answer:

If you are interested in having longer periods for SLP discoveries, you can do so modifying the following configuration elements. All of these files are located in the “/etc” fodler inside the Karaf folder being used:

-mw.connectors.discovery.slp.core.cfg:
   slpPeriodScan = Period in seconds for SLP discoveries
   browseSLPNetwork = true or false. In theory you could set it to false to completely disable SLP, but this is something I have never tested, and I don’t know how the middleware would react.

-mw.modules.aalspace.core.cfg: 
   peerScanPeriod = Period in seconds for the middleware to look for new space configurations. You can put the same amount you put in SLP.

There are other elements involved in periodic scanning (Jgroups UDP) but modifying them takes a bit more effort.

**Comment by amedranogil** [comment]
That is exactly what I have done, 
The server has been running for over a week and there haven't been any broadcast storms.
YET when I launch another uAAL instance it detects it, and does all the ordeal of failing to start the aalspace manager (which BTW bug?).

**Comment by amedranogil** [comment]
solution at: https://github.com/universAAL/platform/wiki/RD-Middleware#run-universaal-middleware-without-network

**Comment by amedranogil** [comment]
@michelegirolami after following the instructions in https://github.com/universAAL/platform/wiki/RD-Middleware#run-universaal-middleware-without-network (correcting "intefaces" for "interfaces", missing "r") I see the GSM logs still locked to local address, and if I look at the opened ports 5555 is opened on all interfaces:
`$ netstat -nl |grep 5555
tcp        0      0 0.0.0.0:5555            0.0.0.0:*               LISTEN  `

This seems to be miss leading information, or outdated. Please confirm.

**Comment by michelegirolami** [comment]
You also have to tell to jGroups to disable the broadcasting of messaging to the network:
here [how to disable jGroups](http://jgroups.org/tutorial/index.html#_using_jgroups_without_a_network)


Basically, you need to add 2 properties:

`-Djgroups.bind_addr=127.0.0.1 -Djava.net.preferIPv4Stack=true`

**Comment by amedranogil** [comment]
I have updated the wiki, although it seems preferIPv4Stack seems to be already a default property configured for uAAL.
It seems to work, GSM lines are now binded to local host.
YET it seems the ports are binded to all interfaces:
```
$ netstat -nl |grep 5555
tcp        0      0 0.0.0.0:5555            0.0.0.0:*               LISTEN     
udp        0      0 0.0.0.0:5555            0.0.0.0:*                          
```
